<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<meta name="description" content="Web Applications Interface">
	<meta name="robots" content="{$robots}" n:ifset="$robots">

	<title>{block title}{/block} :: Web Applications Interface</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$basePath}/css/screen.css" type="text/css">
	<link rel="shortcut icon" href="{$basePath}/favicon.ico" type="image/x-icon">

</head>

<body>
	{foreach $flashes as $flash}<div class="flash {$flash->type}">{$flash->message}</div>{/foreach}

	{include #content}
	<p id="logged-in" n:if="$user->loggedIn">
        Signed in as {$user->identity->name}.
    </p>
</body>
</html>
